name: distnet_huberloss_interns_beholder
description: train a model to regress distances to objects using a CNN
data:
  train_data_dir: /irad_mounts/lambda-quad-5-data/beholder/
  val_data_dir: /irad_mounts/lambda-quad-5-data/beholder/
  make_local: True
hyperparameters:
    learning_rate: 0.000001
    weight_decay: 0.0001
    global_batch_size: 4
    lambda_d: 10
    lambda_k: 0
searcher:
    name: single
    metric: RMSE
    smaller_is_better: true
    max_length:
        batches: 46500
checkpoint_storage:
    host_path: /irad_users/determined
    save_experiment_best: 1
    save_trial_best: 0
    save_trial_latest: 1
    storage_path: checkpoints
    type: shared_fs
resources:
    max_slots: 1
    resource_pool: AMP_48G
    slots_per_trial: 1
environment:
    image: lambda-controller.udev.six3/determinedai/environments:beholder
entrypoint: model_def:DistNetTrial
min_validation_period:
    batches: 2325
min_checkpoint_period:
    batches: 2325
