name: asha_resnet_finetune_interns_beholder
description: use the trained model to train and test on InternData
environment:
  add_capabilities: []
  drop_capabilities: []
  environment_variables:
    cpu:
      - MLFLOW_TRACKING_URI=http://lambda-controller.udev.six3/mlflow
      - GIRDER_URL=http://lambda-controller.udev.six3/girder/api/v1
    cuda:
      - MLFLOW_TRACKING_URI=http://lambda-controller.udev.six3/mlflow
      - GIRDER_URL=http://lambda-controller.udev.six3/girder/api/v1
    rocm:
      - MLFLOW_TRACKING_URI=http://lambda-controller.udev.six3/mlflow
      - GIRDER_URL=http://lambda-controller.udev.six3/girder/api/v1
  force_pull_image: false
  image:
    cpu: lambda-controller.udev.six3/determinedai/environments:beholder
    cuda: lambda-controller.udev.six3/determinedai/environments:beholder
    rocm: lambda-controller.udev.six3/determinedai/environments:beholder
  pod_spec: null
  ports: {}
  slurm: []
bind_mounts:
  - container_path: /irad_share/
    host_path: /irad_share/
    propagation: rprivate
    read_only: false
  - container_path: /uncurated_data/
    host_path: /uncurated_data/
    propagation: rprivate
    read_only: false
  - container_path: /mlruns/
    host_path: /mlruns/
    propagation: rprivate
    read_only: false
  - container_path: /irad_mounts/
    host_path: /irad_mounts/
    propagation: rprivate
    read_only: false
  - container_path: /irad_users/
    host_path: /irad_users/
    propagation: rprivate
    read_only: false
  - container_path: /tmp_host/
    host_path: /tmp/
    propagation: rprivate
    read_only: false
  - container_path: /data/
    host_path: /data/
    propagation: rprivate
    read_only: false
checkpoint_policy: best
checkpoint_storage:
  host_path: /irad_users/determined
  propagation: rprivate
  save_experiment_best: 1
  save_trial_best: 0
  save_trial_latest: 1
  storage_path: checkpoints
  type: shared_fs
data:
  make_local: true
  train_data_dir: /irad_mounts/lambda-quad-5-data/beholder/intern_data/
  val_data_dir: /irad_mounts/lambda-quad-5-data/beholder/intern_data/
data_layer:
  container_storage_path: null
  host_storage_path: null
  type: shared_fs
debug: false
hyperparameters:
  learning_rate: 8.571420e-6
  weight_decay:
    maxval: 0.001
    minval: 0.00001
    type: double
  global_batch_size: 10
  lambda_d: 10
  lambda_k: 0
searcher:
  bracket_rungs: []
  divisor: 4
  max_concurrent_trials: 4
  max_length:
    batches: 1000
  max_rungs: 5
  max_trials: 48
  metric: RMSE
  mode: aggressive
  name: adaptive_asha
  smaller_is_better: true
  source_checkpoint_uuid: null
  source_trial_id: null
  stop_once: false
resources:
  max_slots: 1
  resource_pool: AMP_48G
  slots_per_trial: 1
entrypoint: model_def_resnet_finetune:DistNetTrial
min_validation_period:
  batches: 100
min_checkpoint_period:
  batches: 100
